admin.page_size = 8
server.tomcat.basedir=/var/tmp/clinic
CLIENT_ID = "YOUR_GOOGLE_CLIENT_ID.apps.googleusercontent.com"

momo.partner-code=MOMO
momo.access-key=F8BBA842ECF85
momo.secret-key=K951B6PE1waDMi640xX08PD3vg6EkVlz
momo.endpoint=https://test-payment.momo.vn/v2/gateway/api/create
momo.return-url=https://dab-cryptic-mashing.ngrok-free.dev/clinic/api/payment/momo/return
momo.notify-url= https://dab-cryptic-mashing.ngrok-free.dev/clinic/api/payment/momo/ipn
momo.request-type=captureWallet