admin.page_size=8
avatar.default = https://res.cloudinary.com/dyojjvkxz/image/upload/v1778723190/clinic/avatar/pe1o4c8dihmawxrtz6nx.webp
spring.jackson.serialization.write-dates-as-timestamps=false

CLIENT_ID=1035078432350-ni11amitfec1aso0q77hf0j8aicul2ec.apps.googleusercontent.com

momo.partner-code=MOMO
momo.access-key=F8BBA842ECF85
momo.secret-key=K951B6PE1waDMi640xX08PD3vg6EkVlz
momo.endpoint=https://test-payment.momo.vn/v2/gateway/api/create
momo.return-url=http://localhost:3000/patient/payment-result
momo.notify-url= https://dab-cryptic-mashing.ngrok-free.dev/clinic/api/secure/payments/momo/ipn
momo.request-type=captureWallet

vnpay.tmnCode=WJVJ19R0
vnpay.hashSecret=A9WM2FXJO4O8QMOWYO1ER00X5FGT7OBJ
vnpay.payUrl= https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.returnUrl=http://localhost:3000/patient/payment-result
