users.page_size = 7
doctors.page_size = 7
appointments.page_size = 7
patients.page_size = 7
specialties.page_size = 7
medical_records.page_size = 7
medicines.page_size = 7
notifications.page_size = 7
payments.page_size = 7
prescriptions.page_size = 7
prescription_items.page_size = 7
areas.page_size  = 7
rooms.page_size  = 7
labtests.page_size = 7

CLIENT_ID = "YOUR_GOOGLE_CLIENT_ID.apps.googleusercontent.com"

